### ISSUE TITLE
Fill in the README file

### ISSUE THREAD

**Issue by AliabbasMerchant** [spaceuptech/space-api-python#12]
The README file is what greets people when they see this repo. Let's fill it in.

@Jayesh333 @YourTechBud  
Do you want me to fill it?  
If yes, what content??

**Comment by YourTechBud** [comment]
I really appreciate the initiative! Super cool @AliabbasMerchant

Lets work on the space-api-js repo first. Since we already have something there it will be easier to start with. All the other client repos can have a similar feel with minor variations (language specific nuances)? This will help us maintain consistency!

What say?

**Comment by Jayesh333** [comment]
Yess great idea @AliabbasMerchant @YourTechBud. As of now let's duplicate the readme here with something similar to space-api-js. As an when we get good ideas, we can improve it

**Comment by YourTechBud** [comment]
So lets do this. @AliabbasMerchant, use the readme for space-api-js as a template. Also, let's open up an issue regarding improving the readme on space-api-js so we know it needs to be done! Cool?

Let's leave this issue open till we have a new template!

**Comment by AliabbasMerchant** [comment]
@YourTechBud the Readme on space-api-js seems good enough. Why do we need to update it?

**Comment by YourTechBud** [comment]
As compared to the main space-cloud repo, it still has a lot of scope to improve

**Comment by AliabbasMerchant** [comment]
Ok

**Comment by YourTechBud** [comment]
So let's create the issues and clone the js template for python?

**Comment by AliabbasMerchant** [comment]
Done.  
README updated along with #11
